###

POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

### 

GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcl9pZCI6MiwiaWF0IjoxNzAyMjE0MDIzfQ.JSh5XHrMM4gvVKGw9mggnEkq0LzvEZh9AXEwrUEtQ7g


### 

GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcl9pZCI6MiwiaWF0IjoxNzAyMjE0MDIzfQ.JSh5XHrMM4gvVKGw9mggnEkq0LzvEZh9AXEwrUEtQ7g

###
GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcl9pZCI6MiwiaWF0IjoxNzAyMjE0MDIzfQ.JSh5XHrMM4gvVKGw9mggnEkq0LzvEZh9AXEwrUEtQ7g

###

GET http://localhost:3000/tweets/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcl9pZCI6MiwiaWF0IjoxNzAyMjE0MDIzfQ.JSh5XHrMM4gvVKGw9mggnEkq0LzvEZh9AXEwrUEtQ7g

###
GET http://localhost:3000/tweets/2/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcl9pZCI6MiwiaWF0IjoxNzAyMjE0MDIzfQ.JSh5XHrMM4gvVKGw9mggnEkq0LzvEZh9AXEwrUEtQ7g
###


GET http://localhost:3000/tweets/2/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcl9pZCI6MiwiaWF0IjoxNzAyMjE0MDIzfQ.JSh5XHrMM4gvVKGw9mggnEkq0LzvEZh9AXEwrUEtQ7g
###

GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcl9pZCI6MiwiaWF0IjoxNzAyMjE0MDIzfQ.JSh5XHrMM4gvVKGw9mggnEkq0LzvEZh9AXEwrUEtQ7g
###


POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcl9pZCI6MiwiaWF0IjoxNzAyMjE0MDIzfQ.JSh5XHrMM4gvVKGw9mggnEkq0LzvEZh9AXEwrUEtQ7g

{
   "tweet": "The Mornings..."
}
###


DELETE http://localhost:3000/tweets/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcl9pZCI6MiwiaWF0IjoxNzAyMjE0MDIzfQ.JSh5XHrMM4gvVKGw9mggnEkq0LzvEZh9AXEwrUEtQ7g

###